### ISSUE TITLE
Key Word for Ignoring Spectra in a Profile

### ISSUE THREAD

**Issue by whtowbin** [EFerriss/Pynams#28]
It would be helpful to have an attribute of the Profile class that is a list of bad spectra to ignore when plotting absorbances or calculating diffusion profiles. I was thinking either a list of profiles by index number or by micron position.

**Comment by EFerriss** [comment]
So: add two keywords to profile.plot_area_profile(ignore_idx=[], ignore_pos_microns=[]) that let you pass in a list of indexes (to ignore_idx) or positions (to ignore_pos_microns) that won't get plotted. Other profile methods that would need these keywords: average_spectra() and fitD(). Sound like what you want?

**Comment by whtowbin** [comment]
For the methods (average_spectra(), fitD(), plot_area_profile...) maybe it could just be a keyword such as "ignore_spectra=True". Then the method would look at either the ignore_idx or ignore_pos_microns list. This way it only needs to be entered in one place for each profile.

**Comment by whtowbin** [comment]
One thought to consider is if the ignore_spectra option defaults to true. I imagine if a user is entering data into the ignore_spectra lists they would want it to default to true and then could decide to turn it off it they want to consider those spectra.

**Comment by EFerriss** [comment]
I'm not convinced you need a third keyword here. 
my_list_to_ignore = [0, 3, 10]
profile.plot_area(ignore_idxs=my_list_to_ignore)
# I changed my mind and don't want to ignore anything anymore
profile.plot_area() 
# or
profile.plot_area(ignore_idxs=[])
# or
profile.plot_area(ignore_idxs=None)

This way you have a record of which ones to ignore when you want to, and it's about the same amount of typing as switching True/False but with fewer keywords to keep track of. You can still store the ignore list as an attribute:
profile.ignore = [2, 4, 6]
profile.plot_area(ignore_idxs=profile.ignore)

This way I think will give you a bit more flexibility to easily change which points you are ignoring. I am open to being convinced otherwise.

**Comment by whtowbin** [comment]
I like your second example. That makes sense to me.
My general goal is to be able to define the spectra I wish to ignore in my profile library so it is always an attribute of the Profile in any script it is imported to. I would also have the flexibility to alter that attribute temporarily in a script if needed. 

The True/False would only be useful if you thought it made sense to make True the default. My thinking was that anyone using the ignore setting would want it universally applied for a profile to all methods. That may be wrong, people might want more flexibility to change which spectra are ignored for a particular method.

**Comment by EFerriss** [comment]
Hey, I think the best way for me to avoid a few headaches is to first merge in what I've been doing from the while-working-on-olivine-paper branch and then add these keywords, which means that you will need to update your code to work with my latest version. Virtually all of the changes I've made have been either very minor or having to do with handling whole-block data, so the only thing that I think will matter to you is that I've changed profile.profile_name to just profile.name. You can get that latest from the while-working-on-olivine-paper branch now. I'll merge that into the master branch momentarily.

**Comment by EFerriss** [comment]
master branch now has profile.name in it, and I'm going to start working on this keyword.

**Comment by EFerriss** [comment]
I gotta go, but play with the ignore_idx keyword in profile.plot_area_profile() on the issue28 branch and let me know how it goes.

**Comment by EFerriss** [comment]
ok, now ignore_idx is in all 3 methods we mentioned, although I haven't tested fitD or average_spectra. Let me know if that all solves your problem.

**Comment by EFerriss** [comment]
Have you had a chance to play with these changes yet? If it's ok, I'll merge the issue28 branch back into the master and close this issue.

**Comment by whtowbin** [comment]
plot_area_profile() work really well.

 I haven't used fitD too much before but it doesn't seem to have an effect. Ive even gone to the extreme of ignoring almost all the points in a spectra. 

average_spectra doesn't appear to work at all even when not ignoring spectra. I get an error for line 240 of the profiles module: "spec_list = self.spectra.copy()" 
and the error is: "'list' object has no attribute 'copy'"

**Comment by whtowbin** [comment]
I figured out that I made a mistake when running fitD. Now it works fine for me but average_spectra still gives the same error.

**Comment by EFerriss** [comment]
What was the mistake with fitD?

**Comment by whtowbin** [comment]
It was pretty silly. I used a range function inside of a list and it returned a list within a list. 
Easily fixed

**Comment by EFerriss** [comment]
Can you show me the code you are writing to try out profile.average_spectra()? I am having trouble duplicating the problem. See [the example](https://github.com/EFerriss/Pynams/blob/master/EXAMPLES.ipynb) under "Average all the spectra across the profile"

**Comment by whtowbin** [comment]
Here is the output I get for average = prof.average_spectra()

> average = prof.average_spectra()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-203-e140010132a5> in <module>()
----> 1 average = prof.average_spectra()

/Users/Henry/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/pynams-0.2.0-py2.7.egg/pynams/profiles.pyc in average_spectra(self, ignore_idx)
    238         to ignore_idx
    239         """
--> 240         spec_list = self.spectra.copy()
    241 
    242         # ignore certain data points

AttributeError: 'list' object has no attribute 'copy'

**Comment by whtowbin** [comment]
And Prof is a pynams spectra that plots without problem. 

prof
Out[204]: <pynams.profiles.Profile instance at 0x12c937878>

**Comment by whtowbin** [comment]
Hi E, 
For plot_area_profile() it Looks like the scaling on the Y axes doesn't take into account the ignored spectra list. I like the fact that the X axis doesn't change with the ignored list but it would be helpful if the X axis changed, especially for normalized spectra.

**Comment by EFerriss** [comment]
Are you running python 2.7? I think maybe the average_spectra syntax I had been using to copy a list maybe works in python 3 but not 2.7. Anyway, I changed to something that is more readable, works for me, and hopefully works for you.

**Comment by EFerriss** [comment]
Oh, I see your point with the scaling because if you want to ignore the crazy high point, it would be nice if the y-axis limits weren't set assuming there was still that crazy high point.

**Comment by EFerriss** [comment]
Okey doke. I think that's fixed. Re-reading your last comment here, you say "it would be helpful if the X axis changed" but I think you meant Y axis. I'm going to merge this back issue branch back into the master and close the issue, but do feel free to re-open it if there's more details we didn't cover.
